build-test-release:
  jobs:
    - checkout-code

    - app-build:
        requires:
          - checkout-code

    - publish-github-release:
        requires:
          - app-build
        filters:
          branches:
            only: master
          tags:
            only: /^\d+\.\d+\.\d+$/

    - deploy-npm:
        requires:
          - publish-github-release
        filters:
          branches:
            only: master
          tags:
            only: /^\d+\.\d+\.\d+$/