app-build:
  <<: [*defaults, *node]
  steps:
    - restore_cache:
        key: *source_cache
    - run:
        name: "Authenticate with registry"
        command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - run:
        name: "Install dependencies"
        command: npm install
    - run:
        name: "Build app"
        command: npm run build
    - run:
        name: "Test"
        command: npm run test
    - persist_to_workspace:
        root: *working_directory
        paths: .