checkout-code:
  <<: [*defaults, *node]
  steps:
    - restore_cache:
        keys:
          - source-{{ .Branch }}-{{ .Revision }}
          - source-{{ .Branch }}-
          - source-
    - checkout
    - save_cache:
        key: *source_cache
        paths:
          - *working_directory
