deploy-npm:
  <<: [*defaults, *node]
  steps:
    - attach_workspace:
        at: *working_directory
    - run:
        name: "Authenticate with registry"
        command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - run:
        name: "Publish package"
        command: npm publish
